"use client";

import { useEffect, useMemo, useState } from "react";
import { buildCampaignTwin, DEFAULT_CPM_HYPOTHESES, type CpmHypothesis } from "@/lib/campaign-twin";
import type { MediaGroup } from "@/lib/media-groups";
import { mediaGroupLabel, type PlanningScenario } from "@/lib/plan-optimizer";

export function CampaignTwin({ scenario, budgetUsd, geographies, digitalReady, onApplyBudget }: { scenario: PlanningScenario; budgetUsd: number; geographies: string[]; digitalReady: boolean; onApplyBudget: (value: number) => void }) {
  const [simulationBudget, setSimulationBudget] = useState(budgetUsd);
  const [cpm, setCpm] = useState<Record<MediaGroup, CpmHypothesis>>(DEFAULT_CPM_HYPOTHESES);
  useEffect(() => setSimulationBudget(budgetUsd), [budgetUsd]);
  const allocations = useMemo(() => scenario.allocations.map((item, index) => ({ ...item, amountUsd: index === scenario.allocations.length - 1 ? simulationBudget - scenario.allocations.slice(0, -1).reduce((sum, part) => sum + Math.round(simulationBudget * part.pct * 100) / 100, 0) : Math.round(simulationBudget * item.pct * 100) / 100 })), [scenario.allocations, simulationBudget]);
  const twin = useMemo(() => buildCampaignTwin({ budgetUsd: simulationBudget, allocations, geographies, digitalReady, cpm }), [allocations, cpm, digitalReady, geographies, simulationBudget]);
  const minBudget = Math.max(100, Math.floor(budgetUsd * 0.4));
  const maxBudget = Math.max(minBudget + 100, Math.ceil(budgetUsd * 2.2));

  return <section className="overflow-hidden rounded-panel border border-forest/20 bg-[#102d22] text-white shadow-panel">
    <header className="grid gap-6 border-b border-white/10 p-6 lg:grid-cols-[1fr_auto]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-signal">Gemelo digital de campaña</p><h2 className="mt-2 text-3xl font-black">Mueve una variable y mira el plan reaccionar.</h2><p className="mt-2 max-w-3xl text-sm text-white/60">Simulación trazable: usa la distribución elegida y supuestos CPM editables. No reemplaza forecasts de plataformas, ratings homologados ni cotizaciones.</p></div><div className="rounded-2xl bg-white/10 p-4 text-center"><span className="text-[10px] font-black uppercase text-white/55">Confianza del modelo</span><strong className="mt-1 block text-3xl text-signal">{twin.confidence}%</strong><small className="capitalize text-white/65">{twin.confidenceLabel}</small></div></header>
    <div className="space-y-7 p-6">
      <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl bg-white/8 p-5"><div className="flex items-end justify-between gap-4"><div><span className="text-xs font-black uppercase text-white/55">Presupuesto simulado</span><strong className="mt-1 block text-3xl">{money(simulationBudget)}</strong></div><button type="button" disabled={simulationBudget === budgetUsd} onClick={() => onApplyBudget(simulationBudget)} className="btn btn-primary disabled:opacity-40">Aplicar al plan</button></div><input type="range" min={minBudget} max={maxBudget} step={50} value={simulationBudget} onChange={(event) => setSimulationBudget(Number(event.target.value))} className="mt-5 w-full accent-[#69e075]" /><div className="mt-2 flex justify-between text-[10px] text-white/45"><span>{money(minBudget)}</span><span>{money(maxBudget)}</span></div></div><div className="rounded-2xl bg-signal p-5 text-[#0b2419]"><span className="text-[10px] font-black uppercase">Entrega modelada</span><strong className="mt-2 block text-2xl">{compact(twin.modeledImpressions.low)}–{compact(twin.modeledImpressions.high)}</strong><p className="mt-1 text-xs font-bold opacity-70">impresiones hipotéticas, no alcance deduplicado</p><small className="mt-3 block opacity-65">El rango cambia cuando editas los CPM de trabajo.</small></div></div>

      {twin.optimization && <aside className="rounded-2xl border border-signal/40 bg-signal/10 p-5"><p className="text-xs font-black uppercase text-signal">Oportunidad de redistribución</p><strong className="mt-2 block text-lg">Mover {money(twin.optimization.shiftUsd)} de {mediaGroupLabel(twin.optimization.from)} a {mediaGroupLabel(twin.optimization.to)}</strong><p className="mt-1 text-sm text-white/60">{twin.optimization.reason}</p></aside>}

      <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-xl font-black">Presión por medio</h3><p className="text-xs text-white/50">100 indica el umbral de diversificación del simulador; no es saturación real del proveedor.</p></div><span className="text-[10px] font-bold text-white/45">Edita CPM mínimo y máximo</span></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{twin.media.map((item) => <article key={item.kind} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-start justify-between gap-2"><div><strong>{mediaGroupLabel(item.kind)}</strong><small className="mt-1 block text-white/45">{money(item.amountUsd)} · {percent(item.pct)}</small></div><b className={item.risk === "saturado" ? "text-coral" : item.risk === "vigilar" ? "text-amber" : "text-signal"}>{item.saturation}</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${item.risk === "saturado" ? "bg-coral" : item.risk === "vigilar" ? "bg-amber" : "bg-signal"}`} style={{ width: `${Math.min(100, item.saturation)}%` }} /></div><p className="mt-3 text-xs text-white/55">Modelo: {compact(item.impressions.low)}–{compact(item.impressions.high)} impresiones</p><div className="mt-3 grid grid-cols-2 gap-2"><CpmInput label="CPM bajo" value={item.cpm.low} onChange={(value) => setCpm((current) => ({ ...current, [item.kind]: { ...current[item.kind], low: Math.min(value, current[item.kind].high) } }))} /><CpmInput label="CPM alto" value={item.cpm.high} onChange={(value) => setCpm((current) => ({ ...current, [item.kind]: { ...current[item.kind], high: Math.max(value, current[item.kind].low) } }))} /></div></article>)}</div></div>

      <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl bg-white/5 p-5"><h3 className="font-black">Mapa de inversión territorial</h3><p className="mt-1 text-xs text-white/50">Distribución neutral inicial; prioriza plazas cuando existan datos de demanda o afluencia verificables.</p><div className="mt-4 space-y-3">{twin.geographies.map((geo, index) => <div key={geo.label}><div className="flex justify-between text-xs"><strong>{geo.label}</strong><span>{money(geo.amountUsd)}</span></div><div className="mt-1 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-signal to-sky" style={{ width: `${Math.max(12, geo.planningShare * 100)}%`, opacity: Math.max(.55, 1 - index * .08) }} /></div></div>)}</div></section><section className="rounded-2xl bg-white/5 p-5"><h3 className="font-black">Línea de tiempo operativa</h3><ol className="mt-4 space-y-3">{twin.timeline.map((item, index) => <li key={item.phase} className="grid grid-cols-[32px_1fr] gap-3"><span className="grid size-8 place-items-center rounded-full bg-signal text-xs font-black text-[#0b2419]">{index + 1}</span><div><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{item.phase}</strong><small className="text-signal">{item.period}</small></div><p className="mt-1 text-xs text-white/50">{item.action}</p></div></li>)}</ol></section></div>
      <p className="text-[10px] leading-relaxed text-white/40">Metodología: impresiones = inversión ÷ CPM × 1.000. Los CPM cargados son hipótesis internas editables para análisis de sensibilidad; antes de aprobar se reemplazan por forecasts y fuentes del proveedor. No se deduplican personas entre medios.</p>
    </div>
  </section>;
}

function CpmInput({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-[10px] font-black uppercase text-white/45">{label}<input type="number" min="0.1" step="0.1" value={value} onChange={(event) => onChange(Math.max(.1, Number(event.target.value) || .1))} className="mt-1 h-9 w-full rounded-lg border border-white/10 bg-black/15 px-2 text-sm font-bold text-white" /></label>; }
function money(value: number) { return new Intl.NumberFormat("es-EC", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
function compact(value: number) { return new Intl.NumberFormat("es-EC", { notation: "compact", maximumFractionDigits: 1 }).format(value); }
function percent(value: number) { return `${Math.round(value * 100)}%`; }
