export type TvOfferKind = "programa" | "paquete" | "formato";

export type TvOffer = {
  id: string;
  kind: TvOfferKind;
  day: string;
  title: string;
  schedule: string;
  priceUsd: number | null;
  unit: string;
  market?: string;
  note?: string;
};

export type TvRateCatalog = {
  channelSlug: string;
  lastVerified: string;
  priceBasis: string;
  sourceNote: string;
  offers: TvOffer[];
};

type OfferTuple = [
  kind: TvOfferKind,
  day: string,
  title: string,
  schedule: string,
  priceUsd: number | null,
  unit: string,
  market?: string,
  note?: string,
];

function catalog(
  channelSlug: string,
  lastVerified: string,
  priceBasis: string,
  sourceNote: string,
  rows: OfferTuple[],
): TvRateCatalog {
  return {
    channelSlug,
    lastVerified,
    priceBasis,
    sourceNote,
    offers: rows.map(([kind, day, title, schedule, priceUsd, unit, market, note], index) => ({
      id: `${channelSlug}-${index + 1}`,
      kind,
      day,
      title,
      schedule,
      priceUsd,
      unit,
      market,
      note,
    })),
  };
}

const ECUAVISA = catalog(
  "ecuavisa",
  "Junio de 2026",
  "Tarifa referencial por spot de 30 segundos",
  "Parrilla histórica auditada. IVA, vigencia, disponibilidad, rating homologado y negociación final se reconfirman antes de ordenar.",
  [
    ["programa", "Lun–Vie", "Tnv. La Heredera rr", "05:00", 99, "spot 30 s", "Guayaquil"],
    ["programa", "Lun–Vie", "Tnv. La Heredera rr", "05:00", 90, "spot 30 s", "Quito"],
    ["programa", "Lun–Vie", "Tnv. Carita de Ángel rr", "09:00", 1096.2, "spot 30 s", "Guayaquil"],
    ["programa", "Lun–Vie", "Tnv. Lazos de Amor", "09:00", 1134, "spot 30 s", "Quito"],
    ["programa", "Lun–Vie", "Tnv. If You Love", "15:30", 1986.9, "spot 30 s", "Guayaquil"],
    ["programa", "Lun–Vie", "Tnv. Doctor Milagro", "15:30", 1611, "spot 30 s", "Quito"],
    ["programa", "Lun–Vie", "Tnv. Hermanas", "16:30", 1718.4, "spot 30 s", "Guayaquil"],
    ["programa", "Lun–Vie", "El Amor Más Grande", "16:30", 1772.1, "spot 30 s", "Quito"],
    ["programa", "Lun–Vie", "Amores Verdaderos", "17:30", 1933.2, "spot 30 s", "Guayaquil"],
    ["programa", "Lun–Vie", "Destilando Amor", "18:15", 2255.4, "spot 30 s", "Guayaquil"],
    ["programa", "Lun–Vie", "Destilando Amor", "17:30", 2953.5, "spot 30 s", "Quito"],
    ["programa", "Lun–Vie", "Destiny", "21:00", 4212, "spot 30 s", "Guayaquil"],
    ["programa", "Lun–Vie", "Destiny", "21:00", 3790.8, "spot 30 s", "Quito"],
    ["programa", "Lun–Vie", "Tres Hermanas", "22:00", 3580.2, "spot 30 s", "Guayaquil"],
    ["programa", "Lun–Vie", "Tres Hermanas", "22:00", 2527.2, "spot 30 s", "Quito"],
    ["programa", "Lun–Vie", "Televistazo a la Comunidad", "06:00", null, "spot 30 s"],
    ["programa", "Lun–Vie", "Contacto Directo en Televistazo", "07:00", null, "spot 30 s"],
    ["programa", "Lun–Vie", "Televistazo en la Comunidad", "07:30", null, "spot 30 s"],
    ["programa", "Lun–Vie", "En Contacto", "10:00", null, "spot 30 s"],
    ["programa", "Lun–Vie", "Televistazo II", "13:00", null, "spot 30 s"],
    ["programa", "Lun–Vie", "Los Hackers del Espectáculo", "14:00", null, "spot 30 s"],
    ["programa", "Lun–Vie", "Televistazo Estelar / Televistazo III", "19:00", null, "spot 30 s"],
    ["programa", "Lun–Vie", "Piso 17", "23:00", null, "spot 30 s"],
    ["programa", "Sábado", "Así Pasa rr", "05:00", null, "spot 30 s"],
    ["programa", "Sábado", "Combo Amarillo rr", "05:30", null, "spot 30 s"],
    ["programa", "Sábado", "A-Team rr", "06:00", null, "spot 30 s"],
    ["programa", "Sábado", "Como Dice el Dicho rr", "05:00", null, "spot 30 s"],
    ["programa", "Sábado", "Tnv. Sí Se Puede", "09:30", null, "spot 30 s"],
    ["programa", "Sábado", "Historias de la Virgen Morena", "10:30", null, "spot 30 s"],
    ["programa", "Sábado", "Tnv. Más Sabe el Diablo", "11:30", null, "spot 30 s"],
    ["programa", "Sábado", "Tnv. Carita de Ángel rr", "15:30", null, "spot 30 s"],
    ["programa", "Sábado", "Largometraje", "17:30 / 20:00 / 22:00", null, "spot 30 s"],
    ["programa", "Sábado", "Pan Nuestro", "09:00", null, "spot 30 s"],
    ["programa", "Sábado", "Televistazo", "19:00", null, "spot 30 s"],
    ["programa", "Domingo", "El Hombre Increíble rr", "05:00", null, "spot 30 s"],
    ["programa", "Domingo", "A-Team rr", "06:00", null, "spot 30 s"],
    ["programa", "Domingo", "Como Dice el Dicho", "05:00", null, "spot 30 s"],
    ["programa", "Domingo", "Políticamente Correcto", "10:30", null, "spot 30 s"],
    ["programa", "Domingo", "Esta Semana con Pedro Jiménez", "11:30", null, "spot 30 s"],
    ["programa", "Domingo", "Entre Flashes", "12:30", null, "spot 30 s"],
    ["programa", "Domingo", "A-Team rr", "13:30", null, "spot 30 s"],
    ["programa", "Domingo", "Largometraje", "15:30 / 17:30 / 20:30 / 22:30", null, "spot 30 s"],
    ["programa", "Domingo", "Hacia un Nuevo Estilo de Vida", "08:30", null, "spot 30 s"],
    ["programa", "Domingo", "Panorama Internacional", "09:30", null, "spot 30 s"],
    ["programa", "Domingo", "Televistazo", "19:00", null, "spot 30 s"],
  ],
);

const RED_COMERCIAL = catalog(
  "red-comercial",
  "Agosto de 2026",
  "Tarifa referencial por spot de 30 segundos",
  "Valores de la parrilla comercial RTS/TVC. IVA, vigencia, disponibilidad y negociación final se reconfirman.",
  [
    ["programa", "Lun–Vie", "El Despertar / A Primera Hora", "06:00", 1298, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "La Noticia Primera / TVC Noticias I", "07:00", 2400, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "La Noticia Comunidad / TVC Comunidad", "08:00", 2358, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Noticias Mañana / Buenos Días TVC", "09:30", 2358, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Mujer Casos / Perdóname", "11:00", 1844, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Elif / Privilegio de Amar", "12:00", 1456, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Rosa de Guadalupe I / Ángeles Caen", "13:00", 1979, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Laura / Rosario", "14:00", 1828, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Legado de Amor / Rosa de Guadalupe", "15:00", 2326, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Ángeles Caen / Caso Cerrado II", "16:00", 2568, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Caso Cerrado / Esmeralda", "17:00", 2792, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Esposa por Obligación / Mi Verdad Oculta", "18:00", 4442, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Combate I / Mi Rival", "19:00", 3761, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Combate II / Rosa de Guadalupe I", "20:00", 5560, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Corazón Abandonado II / Rosa de Guadalupe II", "21:00", 6053, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "La Noticia Estelar / TVC Noticias II", "22:00", 5261, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Nueva Novia / Laura", "23:30", 2291, "spot 30 s", "RTS / TVC"],
    ["programa", "Lun–Vie", "Walking Dead / NCIS LA", "24:00", 610, "spot 30 s", "RTS / TVC"],
  ],
);

const TELEAMAZONAS = catalog(
  "teleamazonas",
  "Julio de 2026",
  "Tarifa por spot o paquete, según la fila",
  "Tarifario y paquetes históricos. La parrilla, inclusiones, vigencia, IVA y negociación se reconfirman con el medio.",
  [
    ["programa", "Lun–Vie", "El Chapulín Colorado", "05:00", 400, "spot"],
    ["programa", "Lun–Vie", "El Chavo del 8", "05:30", 400, "spot"],
    ["programa", "Lun–Vie", "24 Horas · Primera Emisión Local", "05:55", 1200, "spot"],
    ["programa", "Lun–Vie", "24 Horas · Nacional I", "07:00", 1200, "spot"],
    ["programa", "Lun–Vie", "Entrevistas", "07:30", 1200, "spot"],
    ["programa", "Lun–Vie", "24 Horas · Segunda Emisión Local", "08:00", 1200, "spot"],
    ["programa", "Lun–Vie", "esTAmañana", "09:30", 1000, "spot"],
    ["programa", "Lun–Vie", "Tnv. Por Amar Sin Ley", "12:00", 1000, "spot"],
    ["programa", "Lun–Vie", "24 Horas", "13:00", 2000, "spot"],
    ["programa", "Lun–Vie", "Comunidad", "13:50", 2000, "spot"],
    ["programa", "Lun–Vie", "En Corto", "14:30", 1000, "spot"],
    ["programa", "Lun–Vie", "Deporte Total", "14:40", 2000, "spot"],
    ["programa", "Lun–Vie", "Bob Esponja", "15:10", 1200, "spot"],
    ["programa", "Lun–Vie", "Doraemon", "15:45", 1200, "spot"],
    ["programa", "Lun–Vie", "Los Simpson", "16:15", 1200, "spot"],
    ["programa", "Lun–Vie", "El Chapulín Colorado", "17:00", 1600, "spot"],
    ["programa", "Lun–Vie", "El Chavo del 8", "17:30", 1600, "spot"],
    ["programa", "Lun–Vie", "Papás por Siempre", "18:00", 1800, "spot"],
    ["programa", "Lun–Vie", "100 Ecuatorianos Dicen", "19:00", 2400, "spot"],
    ["programa", "Lun–Vie", "24 Horas Estelar", "20:00", 3200, "spot"],
    ["programa", "Lunes", "De Lunes a Lunes", "21:00", 1500, "spot"],
    ["programa", "Mar–Vie", "Nuevo Rico, Nuevo Pobre", "21:00", 1500, "spot"],
    ["programa", "Lun–Mié", "El After", "22:30", 1800, "spot"],
    ["programa", "Jue–Vie", "Enchufe TV", "22:30", 1800, "spot"],
    ["paquete", "Paquete", "24 Horas · 49 comerciales", "Según plan", 22000, "paquete"],
    ["paquete", "Paquete", "24 Horas · 22 comerciales", "Según plan", 13200, "paquete"],
    ["paquete", "Paquete", "24 Horas · 11 comerciales", "Según plan", 7700, "paquete"],
    ["paquete", "Paquete", "24 Horas Dominical · 4 comerciales", "Según plan", 7700, "paquete"],
    ["paquete", "Paquete", "Deporte Total", "Mensual", 12000, "paquete mensual"],
    ["paquete", "Paquete", "En Corto", "Mensual", 14000, "paquete mensual"],
    ["paquete", "Paquete", "Deporte Total Estelar", "Mensual", 24000, "paquete mensual"],
    ["paquete", "Paquete", "En Corto Estelar", "Mensual", 24000, "paquete mensual"],
    ["paquete", "Paquete", "Más Fútbol · 2 partidos", "Según calendario", 6000, "paquete"],
    ["paquete", "Paquete", "esTAmañana", "Mensual", 5000, "paquete mensual"],
    ["paquete", "Paquete", "De Lunes a Lunes", "Integral", null, "cotización integral"],
    ["paquete", "Paquete", "100 Ecuatorianos Dicen", "Mensual", 8000, "paquete mensual"],
    ["paquete", "Paquete", "El After", "Mensual", 6000, "paquete mensual"],
    ["paquete", "Paquete", "América Vive", "Mensual", 6000, "paquete mensual"],
    ["paquete", "Paquete", "El Buscador", "Mensual", 6000, "paquete mensual"],
    ["paquete", "Paquete", "Nadie se Salva · 36 comerciales", "Histórico", 40000, "paquete", undefined, "Reconfirmar alcance e inclusiones"],
    ["paquete", "Paquete", "Nadie se Salva · 22 comerciales", "Histórico", 28000, "paquete", undefined, "Reconfirmar alcance e inclusiones"],
    ["paquete", "Paquete", "Nadie se Salva · 15 comerciales", "Histórico", 21000, "paquete", undefined, "Reconfirmar alcance e inclusiones"],
    ["paquete", "Paquete", "Destino Mundial", "Histórico", 2200, "paquete", undefined, "Reconfirmar vigencia"],
    ["paquete", "Paquete", "Escape Perfecto · Auspicio", "Según propuesta", 300000, "paquete"],
    ["paquete", "Paquete", "Escape Perfecto · Especial", "Según propuesta", 180000, "paquete"],
    ["paquete", "Paquete", "Escape Perfecto · Preferencial", "Según propuesta", 100000, "paquete"],
    ["paquete", "Paquete", "Escape Perfecto · Portacuña", "Según propuesta", 2200, "inserción"],
  ],
);

const TC_TELEVISION = catalog(
  "tc-television",
  "Julio de 2026",
  "Tarifa por spot o paquete, según la fila",
  "Parrilla y paquetes comerciales referenciales. IVA, piezas, pauta exacta, vigencia y disponibilidad se reconfirman.",
  [
    ["programa", "Lun–Vie", "DESPIERTC", "05:40–07:00", 650, "spot"],
    ["programa", "Lun–Vie", "Noticiero I", "07:00–08:30", 1200, "spot"],
    ["programa", "Lun–Vie", "Entre Ellas", "08:30–10:00", 800, "spot"],
    ["programa", "Lun–Vie", "De Casa", "10:00–11:30", 550, "spot"],
    ["programa", "Lun–Vie", "Caminos del Amor", "11:30–12:00", 700, "spot"],
    ["programa", "Lun–Vie", "Noticiero II", "12:00–14:00", 900, "spot"],
    ["programa", "Lun–Vie", "Después del Noticiero", "14:00–15:00", 1050, "spot"],
    ["programa", "Lun–Vie", "Hilos de Vida", "15:00–16:00", 580, "spot"],
    ["programa", "Lun–Vie", "Donde Empieza el Amor", "16:00–16:30", 550, "spot"],
    ["programa", "Lun–Vie", "Lilet Matías", "16:30–17:30", 550, "spot"],
    ["programa", "Lun–Vie", "Soy el Mejor", "17:30–19:00", 1000, "spot"],
    ["programa", "Lun–Vie", "Noticiero III", "19:00–21:00", 2500, "spot"],
    ["programa", "Lun–Vie", "El Mofle II", "21:00–21:30", 1700, "spot"],
    ["programa", "Lun–Vie", "Darío Gómez", "21:30–22:00", 1600, "spot"],
    ["programa", "Lun–Vie", "Alerta Roja", "23:00–00:00", 400, "spot"],
    ["programa", "Lun–Vie", "Late", "00:00–02:00", 170, "spot"],
    ["programa", "Lun–Vie", "Madrugada", "02:00–05:40", 90, "spot"],
    ["programa", "Sábado", "Noticiero III rr", "05:00–06:30", 110, "spot"],
    ["programa", "Sábado", "Hechizada", "06:30–07:00", 110, "spot"],
    ["programa", "Sábado", "Mi Bella Genio", "07:00–07:30", 110, "spot"],
    ["programa", "Sábado", "Cine Mágico", "10:00–12:00", 110, "spot"],
    ["programa", "Sábado", "Largometraje", "12:00–14:00", 110, "spot"],
    ["programa", "Sábado", "Mi Bella Genio", "14:00–14:30", 220, "spot"],
    ["programa", "Sábado", "Hechizada", "14:30–15:00", 220, "spot"],
    ["programa", "Sábado", "Largometraje", "15:00–17:00", 220, "spot"],
    ["programa", "Sábado", "Largometraje", "17:00–19:00", 380, "spot"],
    ["programa", "Sábado", "Alerta Roja", "19:00–20:00", 380, "spot"],
    ["programa", "Sábado", "Impacto", "20:00–21:00", 380, "spot"],
    ["programa", "Sábado", "Los de Al Lado rr", "21:00–22:00", 380, "spot"],
    ["programa", "Sábado", "Hechizada", "23:00–23:30", 140, "spot"],
    ["programa", "Sábado", "Mi Bella Genio", "23:30–00:00", 140, "spot"],
    ["programa", "Sábado", "Late", "00:00–02:00", 140, "spot"],
    ["programa", "Sábado", "Madrugada", "02:00–05:00", 70, "spot"],
    ["programa", "Domingo", "Impacto rr", "06:00–07:00", 150, "spot"],
    ["programa", "Domingo", "Luz Clarita", "08:00–10:30", 150, "spot"],
    ["programa", "Domingo", "Cine Mágico", "10:30–12:00", 150, "spot"],
    ["programa", "Domingo", "Hechizada", "12:00–12:30", 150, "spot"],
    ["programa", "Domingo", "Mi Bella Genio", "12:30–13:00", 150, "spot"],
    ["programa", "Domingo", "El Hijo Pródigo", "13:00–15:00", 120, "spot"],
    ["programa", "Domingo", "Máscaras", "15:00–17:00", 120, "spot"],
    ["programa", "Domingo", "Cicatrices", "17:00–18:55", 670, "spot"],
    ["programa", "Domingo", "Noticiero Dominical", "18:55–20:00", 1700, "spot"],
    ["programa", "Domingo", "Verdades Urbanas", "20:00–21:00", 670, "spot"],
    ["programa", "Domingo", "Buenos Muchachos", "21:00–22:00", 670, "spot"],
    ["programa", "Domingo", "TC Deportes", "23:00–23:30", 670, "spot"],
    ["programa", "Domingo", "Al Fondo", "23:30–00:00", 150, "spot"],
    ["programa", "Domingo", "Late", "00:00–02:00", 150, "spot"],
    ["programa", "Domingo", "Madrugada", "02:00–06:00", 80, "spot"],
    ["paquete", "Paquete", "DESPIERTC · El Noticiero", "Según propuesta", 13500, "paquete"],
    ["paquete", "Paquete", "De Casa", "Según propuesta", 13000, "paquete"],
    ["paquete", "Paquete", "Después del Noticiero", "Según propuesta", 16500, "paquete"],
    ["paquete", "Paquete", "Telenovelas A–AA", "Según propuesta", 5000, "paquete"],
    ["paquete", "Paquete", "Telenovela AAA", "Según propuesta", 5400, "paquete"],
    ["paquete", "Paquete", "Soy el Mejor", "Según propuesta", 18000, "paquete"],
    ["paquete", "Paquete", "El Mofle · Mensual", "Mensual", 35000, "paquete"],
    ["paquete", "Paquete", "El Mofle · Temporada", "Temporada", 87500, "paquete"],
    ["paquete", "Paquete", "Mejor Torneo · Full", "Según propuesta", 25000, "paquete"],
    ["paquete", "Paquete", "Mejor Torneo · Half", "Según propuesta", 18500, "paquete"],
    ["paquete", "Paquete", "Mejor Torneo · Básico", "Según propuesta", 13500, "paquete"],
    ["paquete", "Paquete", "Buenos Muchachos · Full", "Según propuesta", 15000, "paquete"],
    ["paquete", "Paquete", "Buenos Muchachos · Half", "Según propuesta", 8000, "paquete"],
  ],
);

const CATOMEDIA = catalog(
  "catomedia-ucsg",
  "Julio de 2026",
  "Tarifa por inserción o paquete",
  "Oferta UCSG TV/Radio/redes. Audiencia, parrilla, IVA, disponibilidad e inclusiones exactas se reconfirman.",
  [
    ["programa", "Lun–Vie", "Hablemos Claro", "08:00", null, "cotización", "YouTube / UCSG TV / Radio"],
    ["programa", "Miércoles", "UCSG al Día", "12:00", null, "cotización"],
    ["programa", "Martes", "Café Walter", "12:00", null, "cotización"],
    ["programa", "Según parrilla", "Consultorio", "Según parrilla", null, "cotización"],
    ["programa", "Jueves", "Nuestra Gente", "12:00", null, "cotización"],
    ["formato", "Inserción", "Logo / placa · 5 segundos", "Según pauta", 25, "inserción"],
    ["formato", "Inserción", "Sobreimposición · 10 segundos", "Según pauta", 25, "inserción"],
    ["formato", "Inserción", "Mención · 15 segundos", "Según pauta", 50, "inserción"],
    ["formato", "Inserción", "Comercial · 20 segundos", "Según pauta", 35, "inserción"],
    ["formato", "Inserción", "Comercial · 30 segundos", "Según pauta", 50, "inserción"],
    ["formato", "Inserción", "Comercial · 45 segundos", "Según pauta", 75, "inserción"],
    ["formato", "Inserción", "Comercial · 60 segundos", "Según pauta", 100, "inserción"],
    ["paquete", "Paquete", "Bronze", "40 radio + 40 editoriales + 8 Instagram", 1000, "paquete"],
    ["paquete", "Paquete", "Silver", "60 radio + 60 editoriales + 12 Instagram + 12 TikTok + 40 TV", 1500, "paquete"],
    ["paquete", "Paquete", "Gold", "100 radio + 100 editoriales + 20 Instagram + 20 TikTok + 100 TV", 2200, "paquete"],
  ],
);

export const TV_RATE_CATALOGS: Record<string, TvRateCatalog> = {
  [ECUAVISA.channelSlug]: ECUAVISA,
  [RED_COMERCIAL.channelSlug]: RED_COMERCIAL,
  [TELEAMAZONAS.channelSlug]: TELEAMAZONAS,
  [TC_TELEVISION.channelSlug]: TC_TELEVISION,
  [CATOMEDIA.channelSlug]: CATOMEDIA,
};

