// Archivo generado por scripts/generate_warner_postbuy.py. No editar a mano.
export type PostbuyPlacement = {
  id: string;
  sourceRow: number;
  name: string;
  channel: "ooh" | "radio" | "btl";
  mediaName: string;
  quantity: number | null;
  mediaRights: number | null;
  monthlyImpacts: number | null;
  mediaLogoUrl: string | null;
  evidenceImageUrl: string | null;
  evidenceStatus: "verified" | "pending";
  sourceNote: string | null;
};

export type WarnerPostbuyCampaign = {
  id: string;
  clientName: string;
  executionMonth: string;
  monthLabel: string;
  campaignName: string;
  status: "completed" | "partial" | "pending";
  oohReach: number | null;
  radioReach: number | null;
  totalReach: number | null;
  sourceFile: string;
  sourceSheet: string;
  placements: PostbuyPlacement[];
};

export const WARNER_POSTBUY_CAMPAIGNS = [
  {
    "id": "21f3bab4-d7c9-5431-b64e-fc02f9a2fb6f",
    "clientName": "Warner Bros. Discovery Ecuador",
    "executionMonth": "2026-01-01",
    "monthLabel": "Enero",
    "campaignName": "Wuthering Heights",
    "status": "completed",
    "oohReach": 0.113,
    "radioReach": null,
    "totalReach": null,
    "sourceFile": "Warner_medios_2026_con_imagenes.xlsx",
    "sourceSheet": "Wuthering Heights",
    "placements": [
      {
        "id": "75cd7d76-166f-593d-9603-cd8aa0416fee",
        "sourceRow": 8,
        "name": "Valla LED · Quito · Av. 6 de Diciembre y Río Coca, diagonal Riocentro Norte (S-0226)",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1100000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/wuthering-heights/08-valla-led-quito-av-6-de-diciembre-y-rio-coca-diagonal-riocentro-norte-s-.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "b40979eb-0060-5774-8f78-52d933c6dc80",
        "sourceRow": 9,
        "name": "Valla LED · Quito · Av. América y Naciones Unidas, frente a Plaza de las Américas (S-1878)",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 812000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/wuthering-heights/09-valla-led-quito-av-america-y-naciones-unidas-frente-a-plaza-de-las-ameri.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "f308bf1c-394f-51d3-8b31-f28d5234cd01",
        "sourceRow": 10,
        "name": "Tótem LED · Área Guayaquil · Riocentro El Dorado",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 5,
        "mediaRights": null,
        "monthlyImpacts": 720000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/wuthering-heights/10-totem-led-area-guayaquil-riocentro-el-dorado.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "69aefaf8-ba39-53b3-b239-bf12c265881a",
        "sourceRow": 11,
        "name": "Tótem LED · Área Guayaquil · Village",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 4,
        "mediaRights": null,
        "monthlyImpacts": 500000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/wuthering-heights/11-totem-led-area-guayaquil-village.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      }
    ]
  },
  {
    "id": "bd3261cc-ff2c-57a1-bc9b-884d1a238f04",
    "clientName": "Warner Bros. Discovery Ecuador",
    "executionMonth": "2026-02-01",
    "monthLabel": "Febrero",
    "campaignName": "The Bride",
    "status": "partial",
    "oohReach": 0.136,
    "radioReach": 0.115,
    "totalReach": 0.2354,
    "sourceFile": "Warner_medios_2026_con_imagenes.xlsx",
    "sourceSheet": "The Bride",
    "placements": [
      {
        "id": "db1ad443-8a5b-54d7-8757-3ff7872b3bf8",
        "sourceRow": 8,
        "name": "Valla LED · Quito · Estadio Atahualpa, Av. 6 de Diciembre",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1400000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/the-bride/08-valla-led-quito-estadio-atahualpa-av-6-de-diciembre.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "5bb84861-223e-5afc-9ce7-034b23f249b9",
        "sourceRow": 9,
        "name": "Tótem LED · Guayaquil · Mall del Sol",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 5,
        "mediaRights": null,
        "monthlyImpacts": 1100000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/the-bride/09-totem-led-guayaquil-mall-del-sol.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "9df5a2aa-f8f0-533b-9082-a2eda9c8e5a5",
        "sourceRow": 10,
        "name": "Tótem LED · Guayaquil · Riocentro Ceibos",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 5,
        "mediaRights": null,
        "monthlyImpacts": 650000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/the-bride/10-totem-led-guayaquil-riocentro-ceibos.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "6b0fbb20-eebd-52c4-af3e-a9e52d523107",
        "sourceRow": 11,
        "name": "Arco · Guayaquil · Supercines Orellana",
        "channel": "btl",
        "mediaName": "Arco",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 175000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Arte del arco de The Bride.\nFoto de ubicación pendiente.\nConfirmar sede: Excel Orellana; correo de producción Ceibos."
      },
      {
        "id": "e5bc9c8c-3ea5-5bec-8021-6e459597c53e",
        "sourceRow": 12,
        "name": "Arco · Quito · Multicines CCI",
        "channel": "btl",
        "mediaName": "Arco",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 220000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Referencia de la misma ubicación.\nImagen de La Momia.\nFoto de The Bride pendiente."
      },
      {
        "id": "4ef09e43-bf1f-5404-9f82-755c91594be3",
        "sourceRow": 13,
        "name": "FM Mundo · Hola Mundo",
        "channel": "radio",
        "mediaName": "FM Mundo",
        "quantity": null,
        "mediaRights": 40,
        "monthlyImpacts": null,
        "mediaLogoUrl": "/postbuy/warner/logos/fm-mundo.png",
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Logo de FM Mundo.\nFuente oficial.\nValidar período: audios de marzo; plan de febrero."
      },
      {
        "id": "90ff4ab4-ca01-5374-b62b-08e9a83d2253",
        "sourceRow": 14,
        "name": "Blue Radio · Encuentro",
        "channel": "radio",
        "mediaName": "Blue Radio",
        "quantity": null,
        "mediaRights": 50,
        "monthlyImpacts": null,
        "mediaLogoUrl": "/postbuy/warner/logos/blue-radio-1013.png",
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Logo de Blue Radio 101.3.\nFuente oficial.\nValidar período: audios de marzo; plan de febrero."
      }
    ]
  },
  {
    "id": "719294d5-749a-5298-9580-5252a74fd2ad",
    "clientName": "Warner Bros. Discovery Ecuador",
    "executionMonth": "2026-03-01",
    "monthLabel": "Marzo",
    "campaignName": "They Will Kill You",
    "status": "completed",
    "oohReach": 0.214,
    "radioReach": null,
    "totalReach": null,
    "sourceFile": "Warner_medios_2026_con_imagenes.xlsx",
    "sourceSheet": "They Will Kill You",
    "placements": [
      {
        "id": "f160eed9-b37e-5893-a90b-d8af96871b5c",
        "sourceRow": 8,
        "name": "Tótem LED · Área Guayaquil · Riocentro El Dorado",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 3,
        "mediaRights": null,
        "monthlyImpacts": 620000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/08-totem-led-area-guayaquil-riocentro-el-dorado.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "275ce6b1-3559-5dd4-825b-3666deb6a5d5",
        "sourceRow": 9,
        "name": "Tótem LED · Área Guayaquil · Riocentro Ceibos",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 3,
        "mediaRights": null,
        "monthlyImpacts": 550000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/09-totem-led-area-guayaquil-riocentro-ceibos.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "e0f93a47-23d8-5193-9ddb-454120596164",
        "sourceRow": 10,
        "name": "Tótem LED · Área Guayaquil · Riocentro Entre Ríos",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 3,
        "mediaRights": null,
        "monthlyImpacts": 465000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/10-totem-led-area-guayaquil-riocentro-entre-rios.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "59bf0ede-a319-57c4-b4ba-5649afbe0b4d",
        "sourceRow": 11,
        "name": "Tótem LED · Área Guayaquil · Riocentro Sur",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 3,
        "mediaRights": null,
        "monthlyImpacts": 700000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/11-totem-led-area-guayaquil-riocentro-sur.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "2b41e211-4136-551e-a7c6-58e8387a9eaa",
        "sourceRow": 12,
        "name": "Tótem LED · Área Guayaquil · Riocentro Norte",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 2,
        "mediaRights": null,
        "monthlyImpacts": 630000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/12-totem-led-area-guayaquil-riocentro-norte.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "4d53f015-0bed-5ebd-bf99-e352b4ebb647",
        "sourceRow": 13,
        "name": "Valla LED · Guayaquil · City Mall",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1250000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/13-valla-led-guayaquil-city-mall.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "e287ddd7-d984-526f-8483-35f1b303b5ac",
        "sourceRow": 14,
        "name": "Valla LED · Guayaquil · Pedro Menéndez",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1300000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/14-valla-led-guayaquil-pedro-menendez.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "e67608bf-b0d6-523d-b5e2-6594cf6437a4",
        "sourceRow": 15,
        "name": "Valla LED · Quito · Estadio Atahualpa",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1400000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/15-valla-led-quito-estadio-atahualpa.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "b4556b91-5028-530d-96cf-3f494292af5f",
        "sourceRow": 16,
        "name": "Valla LED · Quito · Cumbayá",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1260000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/16-valla-led-quito-cumbaya.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "b9411aef-ecef-53ce-9f45-ca818015ea9e",
        "sourceRow": 17,
        "name": "Valla LED · Quito · Av. 6 de Diciembre",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1100000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/17-valla-led-quito-av-6-de-diciembre.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "c5233457-eeb7-515d-9749-6c0816035f64",
        "sourceRow": 18,
        "name": "Valla LED · Quito · Av. de los Shyris",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1000000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/they-will-kill-you/18-valla-led-quito-av-de-los-shyris.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      }
    ]
  },
  {
    "id": "b1d1daca-e9b1-50bc-83f8-a80ecadaded9",
    "clientName": "Warner Bros. Discovery Ecuador",
    "executionMonth": "2026-04-01",
    "monthLabel": "Abril",
    "campaignName": "La Momia",
    "status": "partial",
    "oohReach": 0.27,
    "radioReach": 0.06,
    "totalReach": 0.3138,
    "sourceFile": "Warner_medios_2026_con_imagenes.xlsx",
    "sourceSheet": "La Momia",
    "placements": [
      {
        "id": "9d469239-afcf-5037-9f08-06774cd2d82a",
        "sourceRow": 8,
        "name": "Tótem LED · Guayaquil · Mall del Sol",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 5,
        "mediaRights": null,
        "monthlyImpacts": 1100000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/la-momia/08-totem-led-guayaquil-mall-del-sol.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "112b4138-680d-5a51-8e0c-7933263eb923",
        "sourceRow": 9,
        "name": "Tótem LED · Guayaquil · Riocentro Sur",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 5,
        "mediaRights": null,
        "monthlyImpacts": 800000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/la-momia/09-totem-led-guayaquil-riocentro-sur.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "df3acb7f-bf14-548b-97b2-61a956f128c4",
        "sourceRow": 10,
        "name": "Valla LED · Quito · Diego Vásquez y Juan Celis",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1200000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/la-momia/10-valla-led-quito-diego-vasquez-y-juan-celis.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "7edf10bc-0991-5c63-bfa5-c8a15a9754ee",
        "sourceRow": 11,
        "name": "Valla LED · Quito · Av. 6 de Diciembre y California",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1100000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/la-momia/11-valla-led-quito-av-6-de-diciembre-y-california.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "9cdabb5a-ab04-5b7b-995a-30b79beca0c1",
        "sourceRow": 12,
        "name": "Valla LED · Quito · Av. de los Shyris y El Salvador",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1000000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/la-momia/12-valla-led-quito-av-de-los-shyris-y-el-salvador.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "9bfc0d28-70da-509d-9e02-3f5ddec4fa62",
        "sourceRow": 13,
        "name": "Valla fija troquelada · Guayaquil · Sector Riocentro Norte; Fco Orellana",
        "channel": "ooh",
        "mediaName": "Valla fija troquelada",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 2000000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/la-momia/13-valla-fija-troquelada-guayaquil-sector-riocentro-norte-fco-orellana.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "74246a96-7227-5041-9036-2b4bb59edef7",
        "sourceRow": 14,
        "name": "Mupi · Guayaquil · Jardines del Malecón",
        "channel": "ooh",
        "mediaName": "Mupi",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1200000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Referencia de la misma ubicación.\nImagen de Mortal Kombat 2.\nFoto de La Momia pendiente."
      },
      {
        "id": "81dbffe0-dbd4-5f75-b3fc-396b5583b351",
        "sourceRow": 15,
        "name": "Mupi · Guayaquil · Sucre y García Avilés",
        "channel": "ooh",
        "mediaName": "Mupi",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 900000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Referencia de la misma ubicación.\nImagen de Mortal Kombat 2.\nFoto de La Momia pendiente."
      },
      {
        "id": "f587dc99-3938-50ef-9505-0370689b254c",
        "sourceRow": 16,
        "name": "Mupi · Guayaquil · Mall del Sur",
        "channel": "ooh",
        "mediaName": "Mupi",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1500000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Referencia de la misma ubicación.\nImagen de Mortal Kombat 2.\nFoto de La Momia pendiente."
      },
      {
        "id": "88a75804-d005-5071-a102-e76ddc88d2ef",
        "sourceRow": 17,
        "name": "Mupi · Guayaquil · Carlos Julio Arosemena",
        "channel": "ooh",
        "mediaName": "Mupi",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1300000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Referencia de la misma ubicación.\nImagen de Mortal Kombat 2.\nFoto de La Momia pendiente."
      },
      {
        "id": "37dcff9d-4b07-5a1c-90a4-1951c5b387c9",
        "sourceRow": 18,
        "name": "Arco · Quito · Multicines CCI",
        "channel": "btl",
        "mediaName": "Arco",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1000000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/la-momia/18-arco-quito-multicines-cci.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "80f9baf7-21f6-5614-88e8-3196d761cf24",
        "sourceRow": 19,
        "name": "Arco · Guayaquil · Riocentro Ceibos",
        "channel": "btl",
        "mediaName": "Arco",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 220000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/la-momia/19-arco-guayaquil-riocentro-ceibos.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "f5a50d5e-f8d8-572e-a25c-a9c48d2af351",
        "sourceRow": 20,
        "name": "Arco · Guayaquil · San Marino",
        "channel": "btl",
        "mediaName": "Arco",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 260000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Arte del arco de La Momia.\nPrevisto para San Marino.\nFoto de instalación pendiente."
      },
      {
        "id": "ad05dc2d-e12f-549c-815f-539f95884bb7",
        "sourceRow": 21,
        "name": "Fuego · ¿Qué pasa con Mariela?",
        "channel": "radio",
        "mediaName": "Fuego",
        "quantity": null,
        "mediaRights": 50,
        "monthlyImpacts": null,
        "mediaLogoUrl": "/postbuy/warner/logos/radio-fuego-1065.jpg",
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Logo de Radio Fuego 106.5.\nFuente oficial."
      }
    ]
  },
  {
    "id": "661849d9-9de6-5740-b7f9-fa29ee795106",
    "clientName": "Warner Bros. Discovery Ecuador",
    "executionMonth": "2026-04-01",
    "monthLabel": "Abril",
    "campaignName": "Mortal Kombat 2",
    "status": "completed",
    "oohReach": 0.285,
    "radioReach": null,
    "totalReach": null,
    "sourceFile": "Warner_medios_2026_con_imagenes.xlsx",
    "sourceSheet": "Mortal Kombat 2",
    "placements": [
      {
        "id": "cd4d8c9e-29b0-5544-b86c-cff8b1f5eac1",
        "sourceRow": 8,
        "name": "Tótem LED · Área Guayaquil · Riocentro Norte",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 3,
        "mediaRights": null,
        "monthlyImpacts": 630000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/08-totem-led-area-guayaquil-riocentro-norte.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "ccb18156-a66d-5193-b0a0-a506074f5e2c",
        "sourceRow": 9,
        "name": "Tótem LED · Área Guayaquil · Riocentro El Dorado",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 3,
        "mediaRights": null,
        "monthlyImpacts": 750000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/09-totem-led-area-guayaquil-riocentro-el-dorado.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "29fd33a8-21ab-514b-a7c1-294f218471eb",
        "sourceRow": 10,
        "name": "Tótem LED · Área Guayaquil · Riocentro Sur",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 2,
        "mediaRights": null,
        "monthlyImpacts": 700000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/10-totem-led-area-guayaquil-riocentro-sur.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "25bf9995-7bcc-5ebc-a05b-ff574c3ca75b",
        "sourceRow": 11,
        "name": "Tótem LED · Área Guayaquil · Riocentro Ceibos",
        "channel": "ooh",
        "mediaName": "Tótem LED",
        "quantity": 2,
        "mediaRights": null,
        "monthlyImpacts": 550000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/11-totem-led-area-guayaquil-riocentro-ceibos.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "e2dce8ae-2a5f-5fc0-a50c-0a0f3f34b1d2",
        "sourceRow": 12,
        "name": "Valla LED · Área Guayaquil · Vía a Salitre, sector El Dorado",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1150000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/12-valla-led-area-guayaquil-via-a-salitre-sector-el-dorado.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "23d17f01-1c60-5a32-bdd6-0cb9ba8d4b54",
        "sourceRow": 13,
        "name": "Valla LED · Quito · Av. Morán Valverde, sector Quicentro Sur",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1275000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/13-valla-led-quito-av-moran-valverde-sector-quicentro-sur.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "b97ada53-cd81-5f8c-b7e6-98d42cf39d89",
        "sourceRow": 14,
        "name": "Valla LED · Guayaquil · Av. del Bombero, Ceibos",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1200000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/14-valla-led-guayaquil-av-del-bombero-ceibos.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "71c07ac4-8477-54c1-b514-1db6f5560dae",
        "sourceRow": 15,
        "name": "Valla LED · Guayaquil · Plaza Dañín",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1130000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/15-valla-led-guayaquil-plaza-danin.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "8043249e-bef2-5c67-8b77-33b3be094f14",
        "sourceRow": 16,
        "name": "Valla LED · Guayaquil · José María Egas, puente hacia Samborondón",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1500000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/16-valla-led-guayaquil-jose-maria-egas-puente-hacia-samborondon.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "8269bbe2-8c0f-585a-8ebc-3c26024071bc",
        "sourceRow": 17,
        "name": "Valla LED · Quito · Eloy Alfaro y República",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1300000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/17-valla-led-quito-eloy-alfaro-y-republica.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "b35065b9-0f10-51df-9676-7f8277359270",
        "sourceRow": 18,
        "name": "Mupi · Guayaquil · Jardines del Malecón",
        "channel": "ooh",
        "mediaName": "Mupi",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1200000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/18-mupi-guayaquil-jardines-del-malecon.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "b08e8beb-3e6c-5e49-bf87-26681d46d656",
        "sourceRow": 19,
        "name": "Mupi · Guayaquil · Sucre y García Avilés",
        "channel": "ooh",
        "mediaName": "Mupi",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 900000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/19-mupi-guayaquil-sucre-y-garcia-aviles.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "00de1dcc-9ff1-5399-9c7b-bc7251d00828",
        "sourceRow": 20,
        "name": "Mupi · Guayaquil · Mall del Sur",
        "channel": "ooh",
        "mediaName": "Mupi",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1500000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/20-mupi-guayaquil-mall-del-sur.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "e334aee1-82e8-5205-a219-2b0e7a669271",
        "sourceRow": 21,
        "name": "Mupi · Guayaquil · Carlos Julio Arosemena",
        "channel": "ooh",
        "mediaName": "Mupi",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1300000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/mortal-kombat-2/21-mupi-guayaquil-carlos-julio-arosemena.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      }
    ]
  },
  {
    "id": "5be5eb46-cb03-53ff-be5f-58fbc898c5bb",
    "clientName": "Warner Bros. Discovery Ecuador",
    "executionMonth": "2026-06-01",
    "monthLabel": "Junio",
    "campaignName": "Supergirl",
    "status": "partial",
    "oohReach": 0.3,
    "radioReach": null,
    "totalReach": null,
    "sourceFile": "Warner_medios_2026_con_imagenes.xlsx",
    "sourceSheet": "Supergirl",
    "placements": [
      {
        "id": "cc9e923c-e18b-5761-be6f-05ea23b3ce9f",
        "sourceRow": 8,
        "name": "Valla fija · Guayaquil · Av. del Bombero",
        "channel": "ooh",
        "mediaName": "Valla fija",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 2300000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/supergirl/08-valla-fija-guayaquil-av-del-bombero.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "1a6af9b6-d685-50be-93bc-4eb1cc5c81b5",
        "sourceRow": 9,
        "name": "Valla fija · Guayaquil · Av. Pedro Menéndez",
        "channel": "ooh",
        "mediaName": "Valla fija",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 2500000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/supergirl/09-valla-fija-guayaquil-av-pedro-menendez.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "ee2a603b-e93c-5b5e-9b16-290d437883cd",
        "sourceRow": 10,
        "name": "Valla fija · Quito · América y Brasil",
        "channel": "ooh",
        "mediaName": "Valla fija",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 2200000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/supergirl/10-valla-fija-quito-america-y-brasil.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "a77c65ce-e202-52b1-b735-7b0e9a9f881a",
        "sourceRow": 11,
        "name": "Valla fija · Quito · República y Bourgeois",
        "channel": "ooh",
        "mediaName": "Valla fija",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 2000000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/supergirl/11-valla-fija-quito-republica-y-bourgeois.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "fcd0c76a-48e6-512f-9564-687136d45c24",
        "sourceRow": 12,
        "name": "Mural · Guayaquil · Av. 9 de Octubre (10 × 20 m)",
        "channel": "ooh",
        "mediaName": "Mural",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 3100000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/supergirl/12-mural-guayaquil-av-9-de-octubre-10-20-m.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "89e3e362-ce6a-5a8c-9096-4060b046cbe9",
        "sourceRow": 13,
        "name": "Mural · Quito · Amazonas y Japón, formato horizontal",
        "channel": "ooh",
        "mediaName": "Mural",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1900000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/supergirl/13-mural-quito-amazonas-y-japon-formato-horizontal.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "145b7f63-225a-5348-a136-96c1d53c783c",
        "sourceRow": 14,
        "name": "LED bonificado · Guayaquil · Av. del Bombero",
        "channel": "ooh",
        "mediaName": "LED bonificado",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1200000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Referencia del LED bonificado.\nImagen con otro anunciante.\nFoto de Supergirl pendiente."
      }
    ]
  },
  {
    "id": "9d748224-3143-5124-acfc-c22700c4d111",
    "clientName": "Warner Bros. Discovery Ecuador",
    "executionMonth": "2026-07-01",
    "monthLabel": "Julio",
    "campaignName": "Oak Street",
    "status": "partial",
    "oohReach": 0.175,
    "radioReach": 0.12,
    "totalReach": 0.274,
    "sourceFile": "Warner_medios_2026_con_imagenes.xlsx",
    "sourceSheet": "Oak Street",
    "placements": [
      {
        "id": "16e93b8d-c1cf-56b5-a0c1-4a49cb8eac10",
        "sourceRow": 8,
        "name": "Valla fija troquelada · Guayaquil · Ceibos; av del bombero",
        "channel": "ooh",
        "mediaName": "Valla fija troquelada",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 2300000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/oak-street/08-valla-fija-troquelada-guayaquil-ceibos-av-del-bombero.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "308c9728-0610-54ee-84af-1deeb1c3fb8f",
        "sourceRow": 9,
        "name": "Mupi LED · Guayaquil · Pedro Menéndez",
        "channel": "ooh",
        "mediaName": "Mupi LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 850000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/oak-street/09-mupi-led-guayaquil-pedro-menendez.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "3eec0cdc-3e5b-5922-b286-affed2be1396",
        "sourceRow": 10,
        "name": "Mupi LED · Guayaquil · Mall del Sur",
        "channel": "ooh",
        "mediaName": "Mupi LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 930000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/oak-street/10-mupi-led-guayaquil-mall-del-sur.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "931be548-6909-5bb5-ad79-afa708982a3b",
        "sourceRow": 11,
        "name": "Mupi LED · Guayaquil · Carlos Julio Arosemena",
        "channel": "ooh",
        "mediaName": "Mupi LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 750000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/oak-street/11-mupi-led-guayaquil-carlos-julio-arosemena.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "21bedfd5-1923-5b5c-9c35-5f64114ecf58",
        "sourceRow": 12,
        "name": "Mupi LED · Guayaquil · Boyacá y Ballén",
        "channel": "ooh",
        "mediaName": "Mupi LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 800000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/oak-street/12-mupi-led-guayaquil-boyaca-y-ballen.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "f60b8f53-72a4-54e9-bf5e-eaadf68343ed",
        "sourceRow": 13,
        "name": "Mupi LED · Guayaquil · Av. de las Américas",
        "channel": "ooh",
        "mediaName": "Mupi LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 940000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/oak-street/13-mupi-led-guayaquil-av-de-las-americas.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "3057d4f7-1a3f-5bb6-949a-df6852e89b29",
        "sourceRow": 14,
        "name": "Valla LED · Quito · Naciones Unidas y Amazonas",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 815000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/oak-street/14-valla-led-quito-naciones-unidas-y-amazonas.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotografía de la campaña."
      },
      {
        "id": "1c9f79a8-b3f3-5136-95c3-f264138b8d49",
        "sourceRow": 15,
        "name": "Valla LED · Quito · Gaspar de Villarroel y 6 de Diciembre",
        "channel": "ooh",
        "mediaName": "Valla LED",
        "quantity": 1,
        "mediaRights": null,
        "monthlyImpacts": 1155000,
        "mediaLogoUrl": null,
        "evidenceImageUrl": "/postbuy/warner/evidence/oak-street/15-valla-led-quito-gaspar-de-villarroel-y-6-de-diciembre.webp",
        "evidenceStatus": "verified",
        "sourceNote": "Fotograma de la campaña."
      },
      {
        "id": "4eba2597-7c07-5f9c-8f6b-9e715c28a3b9",
        "sourceRow": 16,
        "name": "FM Mundo ·Café Mundo",
        "channel": "radio",
        "mediaName": "FM Mundo",
        "quantity": null,
        "mediaRights": 66,
        "monthlyImpacts": null,
        "mediaLogoUrl": "/postbuy/warner/logos/fm-mundo.png",
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Logo de FM Mundo.\nFuente oficial.\nValidar período: audios de agosto; plan de julio."
      },
      {
        "id": "b0bd8f4a-0fb3-5097-a78e-b1244525ab8b",
        "sourceRow": 17,
        "name": "Fuego · ¿Qué pasa con Mariela?",
        "channel": "radio",
        "mediaName": "Fuego",
        "quantity": null,
        "mediaRights": 50,
        "monthlyImpacts": null,
        "mediaLogoUrl": "/postbuy/warner/logos/radio-fuego-1065.jpg",
        "evidenceImageUrl": null,
        "evidenceStatus": "pending",
        "sourceNote": "Logo de Radio Fuego 106.5.\nFuente oficial.\nValidar período: audios de agosto; plan de julio."
      }
    ]
  }
] as const satisfies readonly WarnerPostbuyCampaign[];
