-- Ad Mavericks One · Capa auditable de los Excel fuente
-- Ejecutar despues de supabase/schema.sql.
-- No reemplaza las tablas operativas actuales: conserva el origen completo y
-- publica vistas normalizadas para validacion y futuras reimportaciones.

begin;

create table if not exists public.source_workbooks (
  id uuid primary key,
  file_name text not null,
  sha256 text not null unique,
  source_label text not null,
  is_current boolean not null default true,
  imported_at timestamptz not null default now(),
  period_start date,
  period_end date,
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists source_workbooks_one_current_idx
  on public.source_workbooks (source_label)
  where is_current;

create table if not exists public.source_sheet_rows (
  id bigint generated by default as identity primary key,
  workbook_id uuid not null references public.source_workbooks (id) on delete cascade,
  sheet_name text not null,
  source_row integer not null check (source_row > 0),
  cells jsonb not null,
  unique (workbook_id, sheet_name, source_row)
);

create index if not exists source_sheet_rows_lookup_idx
  on public.source_sheet_rows (workbook_id, sheet_name, source_row);

create table if not exists public.advertiser_media_investment (
  id bigint generated by default as identity primary key,
  workbook_id uuid not null references public.source_workbooks (id) on delete cascade,
  source_row integer not null,
  advertiser_name text not null,
  total_general numeric(18, 4),
  internet numeric(18, 4),
  press numeric(18, 4),
  radio numeric(18, 4),
  magazine numeric(18, 4),
  supplement numeric(18, 4),
  television numeric(18, 4),
  pay_tv numeric(18, 4),
  currency char(3) not null default 'USD',
  unique (workbook_id, source_row)
);

create index if not exists advertiser_investment_total_idx
  on public.advertiser_media_investment (total_general desc nulls last);

create table if not exists public.market_media_summary (
  id bigint generated by default as identity primary key,
  workbook_id uuid not null references public.source_workbooks (id) on delete cascade,
  medium text not null,
  estimated_investment numeric(18, 4) not null default 0,
  ad_count integer not null default 0,
  currency char(3) not null default 'USD',
  unique (workbook_id, medium)
);

create table if not exists public.market_monthly_summary (
  id bigint generated by default as identity primary key,
  workbook_id uuid not null references public.source_workbooks (id) on delete cascade,
  period_month date not null,
  estimated_investment numeric(18, 4) not null default 0,
  ad_count integer not null default 0,
  currency char(3) not null default 'USD',
  unique (workbook_id, period_month)
);

create table if not exists public.radio_station_metrics (
  id bigint generated by default as identity primary key,
  workbook_id uuid not null references public.source_workbooks (id) on delete cascade,
  station_name text not null,
  genre text,
  dial text,
  frequency text,
  rating numeric(10, 4),
  share numeric(10, 4),
  rating_audience numeric(14, 4),
  reach_audience numeric(14, 4),
  reach_pct numeric(10, 4),
  exclusive_reach_pct numeric(10, 4),
  audience_rank integer,
  reach_rank integer,
  unique (workbook_id, station_name)
);

create index if not exists radio_metrics_rating_idx
  on public.radio_station_metrics (rating desc nulls last);

create index if not exists radio_metrics_reach_idx
  on public.radio_station_metrics (reach_pct desc nulls last);

create or replace view public.current_advertiser_media_investment
with (security_invoker = true) as
select data.*
from public.advertiser_media_investment data
join public.source_workbooks source on source.id = data.workbook_id
where source.is_current;

create or replace view public.current_market_media_summary
with (security_invoker = true) as
select data.*
from public.market_media_summary data
join public.source_workbooks source on source.id = data.workbook_id
where source.is_current;

create or replace view public.current_market_monthly_summary
with (security_invoker = true) as
select data.*
from public.market_monthly_summary data
join public.source_workbooks source on source.id = data.workbook_id
where source.is_current;

create or replace view public.current_radio_station_metrics
with (security_invoker = true) as
select data.*
from public.radio_station_metrics data
join public.source_workbooks source on source.id = data.workbook_id
where source.is_current;

alter table public.source_workbooks enable row level security;
alter table public.source_sheet_rows enable row level security;
alter table public.advertiser_media_investment enable row level security;
alter table public.market_media_summary enable row level security;
alter table public.market_monthly_summary enable row level security;
alter table public.radio_station_metrics enable row level security;

drop policy if exists source_workbooks_admin_read on public.source_workbooks;
create policy source_workbooks_admin_read on public.source_workbooks
  for select to authenticated using (public.is_platform_admin());

drop policy if exists source_rows_admin_read on public.source_sheet_rows;
create policy source_rows_admin_read on public.source_sheet_rows
  for select to authenticated using (public.is_platform_admin());

drop policy if exists advertiser_media_admin_read on public.advertiser_media_investment;
create policy advertiser_media_admin_read on public.advertiser_media_investment
  for select to authenticated using (public.is_platform_admin());

drop policy if exists market_media_admin_read on public.market_media_summary;
create policy market_media_admin_read on public.market_media_summary
  for select to authenticated using (public.is_platform_admin());

drop policy if exists market_monthly_admin_read on public.market_monthly_summary;
create policy market_monthly_admin_read on public.market_monthly_summary
  for select to authenticated using (public.is_platform_admin());

drop policy if exists radio_metrics_admin_read on public.radio_station_metrics;
create policy radio_metrics_admin_read on public.radio_station_metrics
  for select to authenticated using (public.is_platform_admin());

grant select on public.source_workbooks, public.source_sheet_rows,
  public.advertiser_media_investment, public.market_media_summary,
  public.market_monthly_summary, public.radio_station_metrics to authenticated;

grant select on public.current_advertiser_media_investment,
  public.current_market_media_summary, public.current_market_monthly_summary,
  public.current_radio_station_metrics to authenticated;

commit;
